name = "GitHubActionsUtils"
uuid = "721d7bf2-ce01-488f-b7ad-314e1f6ee951"
authors = ["Julius Krumbiegel <julius.krumbiegel@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
